### PR TITLE
Add IDisposable interface to classes that already implement Dispose()

### PR DESCRIPTION
**Pull request by cpboyd**
I was primarily interested in easy disposal of `GraphicsEx`.
e.g.:
```c#
using (GraphicsEx gx = GraphicsEx.FromGraphics(g))
{
...
}
```

I also did a search for any other class implementing `Dispose()`, but not extending the `IDisposable` interface and only found `License`.

### CODE REVIEW

**Comment by cpboyd** [comment]
Closing because this PR is off of my fork's master branch, which I'm about to push other commits into.

I've forked these changes to their [own idisposable branch](https://github.com/cpboyd/sdf/tree/idisposable) if you'd like me to submit a new PR.

**Comment by ctacke** [comment]
By all means, submit a PR and I'll approve it.

**Comment by cpboyd** [comment]
I'd closed this because GitHub PRs automatically pull in any changes to the branch.

The merge may have muddied the history a bit, since I pulled other PRs into my master after I closed this PRs.

Just to be completely clear, after closing the PR I also pushed [commit ab6b30d](https://github.com/ctacke/sdf/commit/ab6b30d9dc3550342293bd059df76a7138ffc126) which moved `ComTypes` classes from the main OpenNETCF project to OpenNETCF.Drawing.

These classes didn't appear to be used anywhere else within the sdf project, but it may be a breaking change if someone had referenced the `ComTypes` in a project not also referencing OpenNETCF.Drawing.

GitHub now has a "Revert" button for merged PRs, which will create a new commit to revert all changes specifically from this merge. (However, it won't change the history in case people have already synced up to the repo.  The only way to clean-up history would be through a rebase. )

If you want, I can submit a separate PR to specifically revert [commit ab6b30d](https://github.com/ctacke/sdf/commit/ab6b30d9dc3550342293bd059df76a7138ffc126) as I'm not sure if you intended to pull that too.

I apologize for any confusion.

**Comment by ctacke** [comment]
I'll let you make that decision.  Really, if you just want to be added as a dev on the project so you can make the changes directly, I'm fine with that. At this point you're driving more than I am.  I haven't done any Compact Framework development in a couple of years.

**Comment by cpboyd** [comment]
@ctacke If you don't see any problems with it, then there's no need to revert.

If you want to add me as a dev, I'd be happy to help.

**Pull request merged**
